### ISSUE TITLE
Test Build on Windows

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#11]
Currently building on Windows fails.

**Comment by wslafoy** [comment]
Alternative issue:  I need to get my linux box working again.

**Comment by jimjkelly** [comment]
Okay, this should be working now with the latest commit. Give a try and let me know if you have any problems.  I did notice this isn't running on IE right now (some newer features of JavaScript don't seem to be available) so I'll have to tune our build scripts to make it compatible, I'll add an issue for that.
