### ISSUE TITLE
DNS Causes a Redirect to S3 Bucket URL

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#13]
The DNS should simply act as an alias/CNAME, and not redirect.  Investigate.

**Comment by wslafoy** [comment]
I can answer part of this:
Domain registered with Google before I knew I was going to use Amazon. 
Used Amazon Route 53 to try and bridge the gap. 
On Google side: Google uses the four amazon DNS name servers
On Amazon Side:
R53 attempts to use missile.exchange and www.missile.exchange as aliases for the buckets. 

Last week, missile.exchange seemed to be a functional alias. the www sub always has redirected to the S3 bucket URL.  But it is inconsistent

**Comment by wslafoy** [comment]
I switched over the www. bucket to have a total redirect to root website URL instead of the root bucket. 
Not sure if that matters

**Comment by wslafoy** [comment]
This looks like it has resolved, I no longer get a redirect to the bucket endpoint. Will continue testing from other devices

**Comment by jimjkelly** [comment]
Okay, I'll close this for now and we can re-open later.  I actually had a feeling something like that may happen, DNS can be wonky like that at first.
