### ISSUE TITLE
P Value Modifications

### ISSUE THREAD

**Issue by wslafoy** [jimjkelly/missile-defense#14]
I overlooked some minor math errors for P(0), I was focusing on intermediary variables, my mistake!
At line 154 in calc.js:

const PW = (tkp, defensivelayers) => {
    return defensivelayers.reduce((p, c) => p * (1 - c), tkp);

Should be

const PW = (tkp, defensivelayers) => {
    return defensivelayers.reduce((p, c) => p * c, (1-tkp));

This is my mistake, I told you the incorrect math for this I believe! Apologies

**Comment by jimjkelly** [comment]
Okay, this is live now.  Give the changes in the closing commit a gander, especially the changes to the test values, see if those make sense.  Let me know if anything doesn't look right.

**Comment by wslafoy** [comment]
Yeah, I am an idiot, the initial code was correct.
const PW = (tkp, defensivelayers) => {
return defensivelayers.reduce((p, c) => p * (1 - c), tkp);
is correct

It should it end up as
(TKP)(P Def. Layer1)(P Def. Layer2)(PDef. LayerN...) == PW

with the ultimate P(0)== (1-PW) with an additional 1-PW for each offensive layer. Github does not seem to like subscripts, so it is a little weird typing out iterations in math. 

There is still a bit of a logical/intuitive problem with where P(0) actually covers though. This will resolve itself with the Mouseover Displays P value feature though. 


Once warhead numbers are included, either in static or graph form, PW will become a little more complex.
There will be a PW for each offensive system:
PW1=(TKP1)(P Def. Layer1:1)(P Def. Layer1:2)(PDef. Layer1:N...)
PW2=(TKP2)(P Def. Layer2:1)(P Def. Layer2:2)(PDef. Layer2:N...)
Then P(0) = (1-PW1^W1)(1-PW2^W2)(1-PWn^Wn)
 I always have trouble keeping all the iterations and complements straight. Apologies for the repeated math errors, I'll make sure to triple check stuff in the future. 


Thursday I am going to do a big review on math and see what else I overlooked/incorrectly sent over. My bad!

**Comment by jimjkelly** [comment]
No worries.  I actually had a similar issue looking at that same area and went back and forth on what the right way to go was.  I just reverted the commit, it should get pushed live shortly.

Regarding reviewing the math, if you feel comfortable with it, a good way to do it is definitely to write some tests similar to the ones we already have.  They get run on every check in, so if I do something dumb and break something we'll know right away.  :)

**Comment by wslafoy** [comment]
I'll practice writing tests, I'm still very slow with javascript, but it is making a lot more sense now!
The math I wrote above checks out for use

**Comment by jimjkelly** [comment]
Yeah you can always just give me some test case numbers that I can add myself.  Either way.

I've got some work on the number of warheads issue, so hopefully I'll have that checked in tomorrow or Wednesday.

**Comment by wslafoy** [comment]
I'll edit this comment in a few with some good numbers to test!
