### ISSUE TITLE
Test Values

### ISSUE THREAD

**Issue by wslafoy** [jimjkelly/missile-defense#16]
The following test values have also been posted on Desmos, where they can be tested against any number of warheads. They can also be freely modified for other tests. Let me know if it doesn't work for any reason
https://www.desmos.com/calculator/dgiqvuwmf3

Distance in Meters, Yield in Kilotons of TNT equivalent, Hardness in PSI
Y=yield
H=Harness
R=reliability 
W=Warheads
i=Number of Interceptors Committed per Incoming Target
Ptrack = P(track)= Probability of the Defensive System detecting and tracking incoming target
Case 1:

OFFENSE 
For Groundburst Offensive:
Y=750
H=700
CEP=900
R=.8

Equivalent for Notional Offensive:
SSPK=.19019 (this is eq. to the Groundburst Offensive output)
R=.8

Intermediate Variables
SSPK=.19019
TKP=.15215

DEFENSE 1 LAYER

Layer 1:
SSPK = .65
i = 2
Ptrack = .5

OUTPUTS
P(Defensive Layer)=.4388
TKP=.15215 (Repeated here for clarity)
PW=.0854

P(0 at W=1) = .9146
P(0 at W=2) =.8365
P(0 at W=3) =.7651
P(0 at W=4) =.6997

**Comment by jimjkelly** [comment]
Awesome! I'll add these.

**Comment by jimjkelly** [comment]
Okay, so adding these, I actually did have the math wrong for P(0) - the subtraction should have come from the result of PW, and adding that yields the correct results per the values you gave here. I've done that, and added to the test suite with all these values in commit 140c5b9a9c.  Should be good to go  on this.
