### ISSUE TITLE
Range Circles do not save

### ISSUE THREAD

**Issue by wslafoy** [jimjkelly/missile-defense#17]
Whenever I load a save link (http://missile.exchange/?link=eyJtb2RlbEluZGV4IjoiMCIsInRhcmdldCI6eyJsYXRpdHVkZSI6MzcuNzczNDcwNTgwNDc3NDY1LCJsb25naXR1ZGUiOi0xMjIuMzU0NDY2MTg3OTk4MSwiaGFyZG5lc3MiOjEwMH0sImxheWVycyI6eyJvZmZlbnNpdmUiOlt7Im5hbWUiOiJOZXcgb2ZmZW5zaXZlIGxheWVyIiwidHlwZSI6Im5vdGlvbmFsIiwic3NwayI6IjAuOTEiLCJyZWxpYWJpbGl0eSI6IjAuOTkiLCJyYW5nZSI6IjAxMDAwMCJ9XSwiZGVmZW5zaXZlIjpbeyJuYW1lIjoiTmV3IGRlZmVuc2l2ZSBsYXllciIsInNzcGsiOiIwLjkiLCJpbnRlcmNlcHRvcnMiOiIyIiwidHJhY2tpbmciOiIwLjkiLCJyYW5nZSI6IjEwMDAwIn1dfX0= for example), the range circles have reset to the center instead of their previously saved positions

**Comment by jimjkelly** [comment]
Ah, yeah I have to add coordinates per layer.  I'm wrapping up fixing something on Sleuthing from the Internet (Koreans changed their whole page out from under me!) and then I was planning on doing some work on this anyway, I'll fix this first.

**Comment by wslafoy** [comment]
There is absolutely no hurry though. I'm really happy with progress!
