### ISSUE TITLE
Model Switching

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#2]
Provide an option to switch models, which is hidden when models == 1 (or just comment it out?)

**Comment by wslafoy** [comment]
Commented out for now, it would be entirely different models with different equations to support them. Offensive side would stay the same, but there are several different defensive models that try to address more/different variables.

**Comment by jimjkelly** [comment]
So, I feel a bit guilty, but I didn't do the commented out thing and instead did the bit where it just disappears when there's only one model as it is now.  It was actually a bit easier because the type of data passed around wouldn't change, and I think it might just be easier in the long run.  If it seems like a hassle though, let me know and I'll change it.

Basically, P0 instead of being the uppermost model is now an array, and if there is more than one item in that array a selector appears to allow a user to select which one to use.

Adding a new model is pretty easy, I show an example in the comments [here](https://github.com/jimjkelly/missile-defense/commit/b39503bfcc059c848b8d9a78dd0931e611a2278d#diff-39ee29d365e098678a9226a808b9bc7cR188). Basically you just need to add something like:

```javascript
{
    'name': 'New Model',
    'description': 'A description',
    'model': (offensive, defensive, target) => {
        // Whatever your calculations you want in your model
        return result;
    }
}
```

Adding that to the array will make it available.

Let me know what you think.

**Comment by wslafoy** [comment]
Awesome, that works for me! I'll start translating the second model into java to see if it works!

**Comment by jimjkelly** [comment]
Cool!  And just to make sure you don't get stuck on the wrong help or documentation, make sure you are searching for JavaScript not Java. The syntax is very different.  Also, not sure if I mentioned this, but if the syntax of...

```javascript
(argument, another) => {
    return something;
}
```

... seems weird to you, it's just the new ES2015 (ES6 - new JavaScript version) way of making anonymous (unnamed) functions.  It's identical to the following:

```javascript
function(argument, another) {
    return something;
}
```
