### ISSUE TITLE
Allow User to Lock Layer

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#20]

**Comment by jimjkelly** [comment]
So on this, do we think it's better to have the lock on the layer itself, or perhaps a toggle on the layer ordering widget up in the top right?

**Comment by wslafoy** [comment]
Either a toggle on the layer ordering widget or a lock symbol next to each layer as listed within the ordering widget. I think the ability to lock each layer individually (maybe with a global lock as well?) would be helpful, but I think the ordering widget is definitely the best place for it

**Comment by jimjkelly** [comment]
So I just added the per-layer locks, let me know how that looks.  For a global lock, I'm assumign the expected behavior is that clicking it would lock each individual layer, regardless of current status, and disable the individual locks.  Unlocking the global lock would unlock each individual layer and make each one toggleable.   Would a larger lock icon to the left of the ordering widget make sense?

**Comment by wslafoy** [comment]
Looks great, playing with it now. 

For a global lock, clicking it should lock all layers, but not disable individual locks.
That way a user can lock everything and then easily unlock a single one for modification

**Comment by jimjkelly** [comment]
Okay, I added the global lock, I think that should wrap this issue up, let me know if there's something else on it.
