### ISSUE TITLE
Allow User to Long Press Stack of Layers to Select One to Move

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#21]
This would help with issues around a layer being buried under another one.  A long press could cause another layer to "pop" over the other and become active and movable.  A visual cue on the layer border could indicate this happened.

**Comment by wslafoy** [comment]
I think a long-press would be good, but could start confusing the user due to multiple functionalities being tied to mouse clicking. Would it be possible to have a GIMP/Photoshop style way of scooting a layer 'up' or 'down' in the stack?

**Comment by jimjkelly** [comment]
Hmm, like in the layer list on the right?  That might work.  Might be able to do some simple ability to drag to reorder them, having the order on the right reflect the order on the map - although I guess there's the issue of there being separate lists for offensive and defensive layers.  We could merge them, and just have someone select which kind when adding a new layer, although I'm not sure that's great either.  Thoughts?

**Comment by wslafoy** [comment]
Yeah, just something very small with a simple UI.  I imagine something spread vertically as the border between the menus and the maps with a setup like:

[Stack Position #] [Box with Layer Color] [Layername]

Probably need to play around with it though

**Comment by jimjkelly** [comment]
Ah, that's a good idea.  Let me see what I can cook up.

**Comment by wslafoy** [comment]
![hqdefault](https://cloud.githubusercontent.com/assets/24390261/23334426/5831693a-fb6c-11e6-8311-9ed0955fc47f.jpg)

**Comment by jimjkelly** [comment]
I've made some good progress with this, but there are a few kinks to work out.  I did have to rearchitect how data is stored internally, which in turn breaks existing share links.  I suppose at some point we'll need to declare that we want them to work across internal schema changes, and at that point I'll have to write something to version them and be able to migrate between versions in case someone has an old link.

**Comment by wslafoy** [comment]
Fortunately for the time being I treat all links as temporary for this very reason, don't worry about breaking links for a bit.

**Comment by jimjkelly** [comment]
Okay *finally* got this working.  There's still a bug where you need to click the map to get the reordering to take hold, and I'll fix that, but I wanted to get it out there to get feedback on the general way it works and all that jazz.  Should be deployed in a few minutes, let me know what you think.

**Comment by jimjkelly** [comment]
okay, fixed that bug as well, so now it should live reorder the layers on the map as you move them in the box.
