### ISSUE TITLE
Preserve Zoom Level in Shared Link

### ISSUE THREAD

**Issue by wslafoy** [jimjkelly/missile-defense#23]
Defaults to a zoom that is very close in

**Comment by jimjkelly** [comment]
Example link (based on your PSI issue link): http://missile.exchange/?link=eyJtb2RlbEluZGV4IjoiMCIsIm1hcCI6eyJ6b29tIjo0LjQzMTY3NDA1NzM0MTIxfSwidGFyZ2V0Ijp7ImxhdGl0dWRlIjozNS43Mzg4Nzc0NDE5NDExMywibG9uZ2l0dWRlIjoxMjAuMjU3MjUwMzg2ODg0Mzh9LCJsYXllcnMiOnsib2ZmZW5zaXZlIjpbeyJuYW1lIjoiREYtMjFpc2giLCJ0eXBlIjoibm90aW9uYWwiLCJzc3BrIjoiLjc1IiwicmFuZ2UiOiIxNTAwMDAwIiwibGF0aXR1ZGUiOjQwLjE5ODc3NzgzMzczMDQsImxvbmdpdHVkZSI6MTE5LjY2NzQ0NjE5MzY0OTc0LCJyZWxpYWJpbGl0eSI6Ii45NSIsIm51bWJlciI6IjAifSx7Im5hbWUiOiJERi0yMUEgR3JvdW5kIEJ1cnN0IChtYWRlIHVwIHdhcmhlYWQpIiwidHlwZSI6Imdyb3VuZC1idXJzdCIsInJhbmdlIjoiMTUwMDAwMCIsImxhdGl0dWRlIjozMi4xMzc2MDA4NTAyMzcwMSwibG9uZ2l0dWRlIjoxMjEuMjM4ODUwOTUxNjczNTQsInlpZWxkIjoiMTAwMCIsInJlbGlhYmlsaXR5IjoiMC45NSIsImNlcCI6IjIwMCIsIm51bWJlciI6IjAifV0sImRlZmVuc2l2ZSI6W3sibmFtZSI6Ik5vdCBBY3R1YWxseSBhIHJlYWwgc3lzdGVtIiwic3NwayI6Ii43NSIsImludGVyY2VwdG9ycyI6IjEiLCJyYW5nZSI6IjEwMDAwMDAiLCJsYXRpdHVkZSI6MzcuMDM1NzczODU4MjM2NTIsImxvbmdpdHVkZSI6MTMwLjI0NDIwODk4Nzg5NjgsInRyYWNraW5nIjoiLjkifV19LCJhY3RpdmUiOnsib2ZmZW5zaXZlIjpbMV0sImRlZmVuc2l2ZSI6W119fQ==
