### ISSUE TITLE
Hardness (PSI) Resets 

### ISSUE THREAD

**Issue by wslafoy** [jimjkelly/missile-defense#24]
It looks like the Hardness (PSI) value seems to reset to null sometimes when I click outside of the circle generated for a Ground Burst Offensive Layer. I cannot get it to consistently do this, it seems to reset 4 or 5 times in a row, then sticks. 
It seems to be related to clicking and moving the GBOL circle, then clicking outside of the circle? 

Setup included below

http://missile.exchange/?link=eyJtb2RlbEluZGV4IjoiMCIsInRhcmdldCI6eyJoYXJkbmVzcyI6IjUifSwibGF5ZXJzIjp7Im9mZmVuc2l2ZSI6W3sibmFtZSI6IkRGLTIxaXNoIiwidHlwZSI6Im5vdGlvbmFsIiwic3NwayI6Ii43NSIsInJhbmdlIjoiMTUwMDAwMCIsImxhdGl0dWRlIjo0MC4xOTg3Nzc4MzM3MzA0LCJsb25naXR1ZGUiOjExOS42Njc0NDYxOTM2NDk3NCwicmVsaWFiaWxpdHkiOiIuOTUiLCJudW1iZXIiOiIwIn0seyJuYW1lIjoiREYtMjFBIEdyb3VuZCBCdXJzdCAobWFkZSB1cCB3YXJoZWFkKSIsInR5cGUiOiJncm91bmQtYnVyc3QiLCJyYW5nZSI6IjE1MDAwMDAiLCJsYXRpdHVkZSI6MzIuMTM3NjAwODUwMjM3MDEsImxvbmdpdHVkZSI6MTIxLjIzODg1MDk1MTY3MzU0LCJ5aWVsZCI6IjEwMDAiLCJyZWxpYWJpbGl0eSI6IjAuOTUiLCJjZXAiOiIyMDAiLCJudW1iZXIiOiIwIn1dLCJkZWZlbnNpdmUiOlt7Im5hbWUiOiJOb3QgQWN0dWFsbHkgYSByZWFsIHN5c3RlbSIsInNzcGsiOiIuNzUiLCJpbnRlcmNlcHRvcnMiOiIxIiwicmFuZ2UiOiIxMDAwMDAwIiwibGF0aXR1ZGUiOjM3LjAzNTc3Mzg1ODIzNjUyLCJsb25naXR1ZGUiOjEzMC4yNDQyMDg5ODc4OTY4LCJ0cmFja2luZyI6Ii45In1dfSwiYWN0aXZlIjp7Im9mZmVuc2l2ZSI6WzFdLCJkZWZlbnNpdmUiOltdfX0=

**Comment by jimjkelly** [comment]
Fixed. Was a bug with updating the target information, so when dragging the map it was resetting the value.

**Comment by wslafoy** [comment]
Changing the Hardness variable does not work unless another variable changes. 
When the value of Hardness is change, it immediately reverts to the pre-change value. However, when another variable is changed (tested, any variable from either Offensive layer or Defensive Layer), the hardness is 'updated' to reflect the new change.

As long as another variable input field is opened and the committed after Hardness should change, Hardness changes.

**Comment by jimjkelly** [comment]
Ah, fixed!
