### ISSUE TITLE
Layer Defaults to Target, but Moves When Target Moves

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#26]
Essentially we're defaulting to target when the layer doesn't specify, so that means it moves with the target, which is undesirable. I guess specifying at layer creation time is necessary.

**Comment by wslafoy** [comment]
This may be something to combine with issue #20, adding a "Lock Layer to Location" seems like it would fix both at once, unless I am misunderstanding this particular issue

**Comment by jimjkelly** [comment]
Well it would have as an option, but the issue was that by default there was no location on a layer until you moved it - so if you added a new layer then moved the map, a layer that hadn't yet been moved would move with the map.  That may not make any sense - heh.  But it's fixed now.  :)
