### ISSUE TITLE
Mouseover Layer Shows P Value

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#4]
On a mouseover, compute probability at that position, given the layers that exist there.

**Comment by wslafoy** [comment]
I think this is my biggest priority right now. 
Once we can get mouseover P values, hopefully we can get mouseover P values of intersections, which will be a hugely valuable capability for the site!

Also having Mouseover P Values is going to change the requirements for on-screen equations/output real estate a lot.

**Comment by jimjkelly** [comment]
Yeah after the number of warheads this is my next priority.  Just need to figure out some issues around detecting and displaying the involved layers.

**Comment by jimjkelly** [comment]
So I have most of this done and released, I want to get your eyes on it so you can see what you may want to tweak on it.  Basically right now it's showing the layer value itself (the same as what is displayed with the layer on the right) and below that it shows the combined value for all the layers where your mouse is (so basically what is on the right as P(0) in the target area, except dynamic for where the mouse is).  Let me know if the values don't seem right, or you want the text changed or anything.

From a technical standpoint the two things I still intend to fix are the fact that it shows up as part of the layer, so it can be under other layers currently, also the box sizing is a little wonky.  I'll probably just have to break it out into it's own thing so it can always be on top. 

If you see other technical problems, or as I mentioned above copy problems, let me know.

**Comment by wslafoy** [comment]
Website isn't loading now unfortunately

**Comment by jimjkelly** [comment]
Hmm, maybe shift reload? Loading on my end.

**Comment by wslafoy** [comment]
good call, my bad! Working now, and is great.
Only other issue I can see is that the box centers on the middle of the layer. I'm playing around with it though, I think that ends up being ideal even if a user can hypothetically zoom in to the point where they can't see the box. I'll test it with some folks and see if they complain, I think this actually is good and keeps the interface clean.

**Comment by jimjkelly** [comment]
I have a fix for the always on top issue, and I also changed it so it follows the mouse. It's easy to change it back to centering on the layer, so try it out and let me know which you prefer. 

Unfortunately I lost internet at home though, so I can't push it live just yet.

**Comment by jimjkelly** [comment]
Yay, internet has returned.  I pushed those changes live, so now it's always on top and follows the mouse.  Let me know what you think.  Still need to make some adjustments to the box sizing.

**Comment by jimjkelly** [comment]
Okay, have the box sizing working, or at least better than it was.  Interactions between text and boxes aren't the strong suit of SVG graphics it seems.  I think this is all wrapped up - let me know if there are any issues or if you want any changes with it.
