### ISSUE TITLE
Modify Layer Color Based on Probability

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#5]
Give a hue adjustment based on the probability of the layer.

**Comment by wslafoy** [comment]
This is a good idea. 
If this is enabled, we should think about having some sort of visual cue for various layers (like different off/def layers have different outlines/dots, for example)

**Comment by jimjkelly** [comment]
This is done and live.  I added varying sized dashes per layer, and the layer colors are represented in a little legend at the top left of the screen.  Going to close, but feel free to let me know if there's anything about it you'd like changed.
