### ISSUE TITLE
Zooming Moves Target

### ISSUE THREAD

**Issue by jimjkelly** [jimjkelly/missile-defense#8]
Target should say in same position when zooming.

**Comment by wslafoy** [comment]
After seeing how well the Offensive and Defensive layers are represented, I'm wondering if the Target UI element may be superfluous. I'm going to get some colleagues to check it out sometime after Finals (Dec.12) and see how they respond to it without prompting/additional explanation.

**Comment by jimjkelly** [comment]
Yeah I think having at least a central dot might be useful?  Would be good to get feedback though.  I'm definitely going to remove the radius bit at least.

**Comment by jimjkelly** [comment]
Looks like another user just [reported](https://github.com/mapbox/mapbox-gl-js/issues/3780) wanting the same ability in the library.  Will have to keep an eye on that, perhaps submit a PR.

**Comment by wslafoy** [comment]
Some limited testing with users indicates the middle target dot, while cool, may not actually be that helpful. I've been sketching out some alternative options, may end up going for no target dot and switching the Offensive (Red) Ring from representing the CEP to representing the offensive missile system's range. Doing some logic tests with users to see if that makes more sense

**Comment by jimjkelly** [comment]
Okay, I'll remove the target dot entirely then, that makes it easier.  Once you have a handle on it, let me know what you want to do about the CEP/range thing.

**Comment by wslafoy** [comment]
Confirmed, red ring should change from representing CEP to representing the offensive missile system's range, makes the visuals way more logical for users. It also fixes some of the logical problems with the Notional Offensive layer not having a CEP function and thus having only a default circle.

This will also require adding Range to both Notional and Ground Burst layers.

**Comment by jimjkelly** [comment]
Okay, I added that.

**Comment by jimjkelly** [comment]
(it'll take a few minutes for it to be deployed)

**Comment by jimjkelly** [comment]
Also removed the target.  I think I can close this issue now - if not let me know!

**Comment by wslafoy** [comment]
Ranges confirmed working, but Target/Center dot still appearing on my end.

**Comment by jimjkelly** [comment]
Oh, oops, didn't delete the Target widget from the code so the linter complained and failed the deploy. I cleaned it up and it'll get pushed with #5 later today.

**Comment by jimjkelly** [comment]
The target is gone now on the production version.
